# coding:utf-8
# 测试用例

case_guanjia_old/case01_guanjia_login.py
#case_guanjia_old/case02_guanjia_get_sms.py
case_guanjia_old/case03_guanjia_modifypwd.py
case_guanjia_old/case04_guanjia_account_info.py
case_guanjia_old/case05_guanjia_user_avatar.py
case_guanjia_old/case06_guanjia_signature.py
case_guanjia_old/case07_guanjia_version_update.py
case_guanjia_old/case08_guanjia_add_client.py
case_guanjia_old/case09_guanjia_personal_info.py
case_guanjia_old/case10_guanjia_community_list.py
case_guanjia_old/case11_guanjia_home_total.py
case_guanjia_old/case12_guanjia_subscribe_lists.py
case_guanjia_old/case13_guanjia_subscribe_detail_info.py
case_guanjia_old/case14_guanjia_subscribe_updateLog.py
case_guanjia_old/case15_guanjia_subscribe_handle.py
case_guanjia_old/case16_guanjia_subscribe_dohandle.py
case_guanjia_old/case17_guanjia_urge_meter.py
case_guanjia_old/case18_guanjia_urge_lists.py
case_guanjia_old/case19_guanjia_repair_info.py
case_guanjia_old/case20_guanjia_repair_lists.py
case_guanjia_old/case21_guanjia_repair_logs.py
case_guanjia_old/case22_guanjia_repair_handle.py
case_guanjia_old/case23_guanjia_repair_dohandle.py
case_guanjia_old/case24_guanjia_repair_state.py
case_guanjia_old/case25_guanjia_urge_signing.py


case_guanjia_new/case01_guanjia_rent_scatList.py
case_guanjia_new/case02_guanjia_rent_centralizedList.py
case_guanjia_new/case03_guanjia_subscribe_lists.py
case_guanjia_new/case04_guanjia_sign_homepage.py
case_guanjia_new/case05_guanjia_rent_userlist.py
case_guanjia_new/case06_guanjia_rent_book_create.py
case_guanjia_new/case07_guanjia_rent_book_docreate.py
case_guanjia_new/case08_guanjia_rent_sign_bill.py
case_guanjia_new/case09_guanjia_rent_sign_submit.py
case_guanjia_new/case10_guanjia_rent_reside_index.py
case_guanjia_new/case11_guanjia_rent_reside_checkuser.py
case_guanjia_new/case12_guanjia_rent_reside_bill.py
case_guanjia_new/case13_guanjia_rent_reside_submit.py
case_guanjia_new/case14_guanjia_rent_change_index.py
case_guanjia_new/case15_guanjia_rent_change_house.py
case_guanjia_new/case16_guanjia_rent_change_bill.py
case_guanjia_new/case17_guanjia_rent_change_check.py
case_guanjia_new/case18_guanjia_rent_change_submit.py
case_guanjia_new/case19_guanjia_rent_relet_index.py
case_guanjia_new/case20_guanjia_rent_relet_bill.py
case_guanjia_new/case21_guanjia_rent_relet_submit.py
case_guanjia_new/case22_guanjia_elemeter_curramount.py
case_guanjia_new/case23_guanjia_rent_payment_lists.py
case_guanjia_new/case24_guanjia_rent_payment_meter.py
case_guanjia_new/case25_guanjia_rent_order_billinfo.py
case_guanjia_new/case26_guanjia_rent_order_create.py
case_guanjia_new/case27_guanjia_rent_house_detail.py
case_guanjia_new/case28_guanjia_rent_house_meter.py



#case_guanjia_old/
#case_guanjia_old/




#case_guanjia_new/case04_guanjia_sign_homepage.py





